### ISSUE TITLE
Cripto - nodistinguisher

### ISSUE THREAD

**Issue by dvolvox** [SuperVirus/CTF#1]
Hi after I run your script this error message is displayed:

  File "nodis2.py", line 27, in <module>
    xortext += bytearray([encrypted[i] ^ intermediatekey[i%8]])
TypeError: unsupported operand type(s) for ^: 'str' and 'str'

**Comment by dvolvox** [comment]
Sorry It was for python3 not 2.7.

**Comment by supervirus** [comment]
Sorry, I forgot to add the README file... Thanks for the reminder.
